Repository AY2526S1-CS2103T-W09-2/tp, pull requests merged in 2025-10, with the labels that each got.

#10 task: Add Javier's Profile photo
  docs/images/jav65.png
Labels: type.Task

#19 Add Xiaoqi's photo
  docs/images/xiaoqi01010.png
Labels: type.Task

#14 Add Oad's Photo
  docs/images/oadultradeepfield.png
Labels: type.Task

#12 Add Butanol's Photo
  docs/images/butanol.png
Labels: type.Task

#29 Update AboutUs.md
  docs/AboutUs.md
  docs/team/butanol.md
Labels: type.Task

#45 Update Github badge on README
  README.md
Labels: type.Task, priority.High

#50 task-update-aboutus-yueyang
  docs/AboutUs.md
  docs/team/chewy03.md
Labels: type.Task

#52 Update README.md
  README.md
Labels: type.Task, priority.High

#44 Add non-functional requirements
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#48 docs: add target user profile, value proposition, and user stories to DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#49 Update DeveloperGuide.md with Non-Functional Requirements.
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#53 chore: Clean-up to finalise milestone v1.1
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/team/chewy03.md
Labels: priority.Low
